### ISSUE TITLE
ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by ShilangChen1011** [beijixiong3510/OWM#5]
Running the "/media/hdd/yike/OWM/Disjoint MNIST/OWM/run_dis_mnist_2Layers.py".
It occurs the following errors:
```
Traceback (most recent call last):
  File "/media/hdd/yike/OWM/Disjoint MNIST/OWM/run_dis_mnist_2Layers.py", line 27, in <module>
    mnist = input_data.read_data_sets("./data/MNIST_data/", one_hot=True)
  File "/home/gzz/.local/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py", line 240, in read_data_sets
    source_url + TRAIN_IMAGES)
  File "/home/gzz/.local/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py", line 208, in maybe_download
    temp_file_name, _ = urlretrieve_with_retry(source_url)
  File "/home/gzz/.local/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py", line 165, in wrapped_fn
    return fn(*args, **kwargs)
  File "/home/gzz/.local/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py", line 190, in urlretrieve_with_retry
    return urllib.request.urlretrieve(url, filename)
  File "/media/hdd/yike/anaconda3/envs/own/lib/python3.5/urllib/request.py", line 188, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/media/hdd/yike/anaconda3/envs/own/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/media/hdd/yike/anaconda3/envs/own/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/media/hdd/yike/anaconda3/envs/own/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/media/hdd/yike/anaconda3/envs/own/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/media/hdd/yike/anaconda3/envs/own/lib/python3.5/urllib/request.py", line 1297, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/media/hdd/yike/anaconda3/envs/own/lib/python3.5/urllib/request.py", line 1257, in do_open
    r = h.getresponse()
  File "/media/hdd/yike/anaconda3/envs/own/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/media/hdd/yike/anaconda3/envs/own/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/media/hdd/yike/anaconda3/envs/own/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/media/hdd/yike/anaconda3/envs/own/lib/python3.5/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
  File "/media/hdd/yike/anaconda3/envs/own/lib/python3.5/ssl.py", line 937, in recv_into
    return self.read(nbytes, buffer)
  File "/media/hdd/yike/anaconda3/envs/own/lib/python3.5/ssl.py", line 799, in read
    return self._sslobj.read(len, buffer)
  File "/media/hdd/yike/anaconda3/envs/own/lib/python3.5/ssl.py", line 583, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer
```

**Comment by ShilangChen1011** [comment]
Resolved.
